tasks:
  - name: "Run program"
    command: |
      # Install bashbox
      curl --proto '=https' --tlsv1.2 -sSfL "https://git.io/Jc9bH" | bash -s selfinstall;
      printf "\033[3J\033c\033[3J";
      source ~/.bashbox/env;

      # Run
      bashbox run --release
